### PR TITLE
Updates jna.

### PR DESCRIPTION
**Pull request by bgrozev**

### CODE REVIEW

**Comment by licaon-kter** [comment]
Any blockers for this?

Ref. https://github.com/jitsi/jitsi-videobridge/issues/1190

**Comment by bgrozev** [comment]
> Any blockers for this?

I just haven't tested it

**Comment by JonathanLennox** [comment]
A quick test with jitsi-srtp shows that it still successfully loads its native library after this update, and builds with no new warnings, so I think this is fine.

**Comment by JonathanLennox** [comment]
Jenkins, test this please.

**Pull request merged**
