### PR TITLE
chore: Another attempt to fix deployment to mavencentral.

### PR DESCRIPTION
**Pull request by bgrozev**

### CODE REVIEW

**Review by ibauersachs — CHANGES_REQUESTED** [review]
I think it would make more sense to move the nexus-staging-maven-plugin into the release profile (which is activated with the property) and remove the -P flag.

**Review by ibauersachs — APPROVED** [review]

**Comment by bgrozev** [comment]
Okay, we're back to a failure `trying to close staging repository`.

**Comment by ibauersachs** [comment]
Yes, OSSRH has massive issues. Not much we can do atm. See https://status.maven.org/

**Comment by ibauersachs** [comment]
Up again and deployed.

**Pull request merged**
